spring:
  application:
    name: tutor-appointment-service
  profiles:
    active: dev
  cloud:
    nacos:
      username: ${NACOS_USERNAME:}
      password: ${NACOS_PASSWORD:}
      config:
        server-addr: ${NACOS_SERVER_ADDR:111.228.20.88:8848}
        group: DEFAULT_GROUP
        namespace: ${NACOS_CONFIG_NAMESPACE:${NACOS_NAMESPACE:beacf12a-2e06-43ae-80f1-6579081850a1}}
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:111.228.20.88:8848}
        namespace: ${NACOS_DISCOVERY_NAMESPACE:${NACOS_NAMESPACE:beacf12a-2e06-43ae-80f1-6579081850a1}}
  config:
    import:
      - optional:nacos:ai-tutor-common.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:ai-tutor-common-${spring.profiles.active}.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:ai-tutor-home.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:ai-tutor-home-${spring.profiles.active}.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:ai-tutor-sms.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:ai-tutor-sms-${spring.profiles.active}.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:${spring.application.name}.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:file:./.private/tutor-appointment-service.yml
      - optional:file:../.private/tutor-appointment-service.yml

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

mybatis:
  mapper-locations: classpath:mapper/*.xml

springdoc:
  packages-to-scan: com.ai.tutor.appointment.controller
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.web: DEBUG

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.JacksonTypeHandler

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
