spring:
  application:
    name: payment-service
  profiles:
    active: dev
  config:
    import:
      - optional:nacos:ai-tutor-common.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:ai-tutor-common-${spring.profiles.active}.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:ai-tutor-payment.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:ai-tutor-payment-${spring.profiles.active}.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:${spring.application.name}.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml?group=DEFAULT_GROUP&refreshEnabled=true
  cloud:
    nacos:
      config:
        server-addr: 106.52.179.248:8848
        group: DEFAULT_GROUP
        namespace: ${NACOS_CONFIG_NAMESPACE:${NACOS_NAMESPACE:3066af4f-57ee-4f4d-80fe-0d2a4e791f7d}}
      discovery:
        server-addr: 106.52.179.248:8848
        namespace: ${NACOS_DISCOVERY_NAMESPACE:${NACOS_NAMESPACE:3066af4f-57ee-4f4d-80fe-0d2a4e791f7d}}
