spring:
  application:
    name: ai-tutor-gateway
  profiles:
    active: dev
  config:
    import:
      - optional:nacos:ai-tutor-common.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:ai-tutor-common-${spring.profiles.active}.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:${spring.application.name}.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml?group=DEFAULT_GROUP&refreshEnabled=true
  cloud:
    nacos:
      username: ${NACOS_USERNAME:}
      password: ${NACOS_PASSWORD:}
      config:
        server-addr: ${NACOS_SERVER_ADDR:111.228.20.88:8848}
        group: DEFAULT_GROUP
        namespace: ${NACOS_CONFIG_NAMESPACE:${NACOS_NAMESPACE:481e4376-4576-4b18-ac19-f61e170ca3ae}}
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:111.228.20.88:8848}
        namespace: ${NACOS_DISCOVERY_NAMESPACE:${NACOS_NAMESPACE:481e4376-4576-4b18-ac19-f61e170ca3ae}}
    gateway:
      httpclient:
        pool:
          type: DISABLED
      routes:
        - id: appointment-user-route
          uri: lb://tutor-appointment-service
          predicates:
            - Path=/user/**
        - id: appointment-api-route
          uri: lb://tutor-appointment-service
          predicates:
            - Path=/api/**
        - id: appointment-domain-route
          uri: lb://tutor-appointment-service
          predicates:
            - Path=/appointment/**,/org/**,/invite/**
        - id: im-chat-route
          uri: lb://videoCall-IM-service
          predicates:
            - Path=/chat/**
        - id: payment-route
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
