CREATE TABLE IF NOT EXISTS `user_email` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '邮箱绑定记录id',
  `user_id` bigint(20) UNSIGNED NOT NULL COMMENT '用户id',
  `email_type` varchar(32) NOT NULL COMMENT '邮箱类型 PRIMARY主邮箱 SUMMARY_ONLY课后总结专用邮箱',
  `email` varchar(255) NOT NULL COMMENT '邮箱地址',
  `email_masked` varchar(255) DEFAULT NULL COMMENT '脱敏邮箱',
  `verify_status` varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '验证状态 PENDING待验证 VERIFIED已验证 INVALID已失效',
  `verified_at` datetime(3) DEFAULT NULL COMMENT '验证通过时间',
  `bind_source` varchar(32) DEFAULT NULL COMMENT '绑定来源 MY_PAGE/COURSE_PAGE/CHAT_PAGE/SUMMARY_PAGE',
  `bounce_status` varchar(32) NOT NULL DEFAULT 'NORMAL' COMMENT '退信状态 NORMAL正常 SOFT_BOUNCE软退信 HARD_BOUNCE硬退信',
  `last_notify_at` datetime(3) DEFAULT NULL COMMENT '最近一次业务通知发送时间',
  `status` tinyint(4) NOT NULL DEFAULT 1 COMMENT '状态 1有效 0删除',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_user_email_type_active` (`user_id`, `email_type`, `status`),
  KEY `idx_email` (`email`),
  KEY `idx_user_type_status` (`user_id`, `email_type`, `verify_status`),
  KEY `idx_bounce_status` (`bounce_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户邮箱绑定表';

CREATE TABLE IF NOT EXISTS `email_verify_code` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '邮箱验证码id',
  `user_id` bigint(20) UNSIGNED NOT NULL COMMENT '用户id',
  `email` varchar(255) NOT NULL COMMENT '目标邮箱',
  `email_type` varchar(32) NOT NULL COMMENT '邮箱类型 PRIMARY/SUMMARY_ONLY',
  `code_hash` varchar(128) NOT NULL COMMENT '验证码hash',
  `scene` varchar(32) NOT NULL COMMENT '场景 BIND/CHANGE/REBIND',
  `expire_at` datetime(3) NOT NULL COMMENT '过期时间',
  `verified_at` datetime(3) DEFAULT NULL COMMENT '验证成功时间',
  `try_count` int(11) NOT NULL DEFAULT 0 COMMENT '验证尝试次数',
  `send_ip` varchar(64) DEFAULT NULL COMMENT '发送请求ip',
  `status` varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '状态 PENDING/VERIFIED/EXPIRED/CANCELED',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_user_email_type_status` (`user_id`, `email`, `email_type`, `status`),
  KEY `idx_expire_at` (`expire_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='邮箱验证码表';

CREATE TABLE IF NOT EXISTS `email_notification_task` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '邮件通知任务id',
  `task_key` varchar(128) NOT NULL COMMENT '业务幂等key',
  `template_code` varchar(64) NOT NULL COMMENT '模板编码',
  `biz_type` varchar(64) NOT NULL COMMENT '业务类型 EMAIL_VERIFY/UNREAD_MESSAGE/LESSON_START/LESSON_SUMMARY',
  `biz_id` bigint(20) UNSIGNED DEFAULT NULL COMMENT '业务id，如msgId或lessonId',
  `receiver_uid` bigint(20) UNSIGNED DEFAULT NULL COMMENT '收件用户id',
  `receiver_role` varchar(32) DEFAULT NULL COMMENT '收件角色 TEACHER/STUDENT/PARENT_SUMMARY',
  `email_type` varchar(32) DEFAULT NULL COMMENT '邮箱类型 PRIMARY/SUMMARY_ONLY',
  `email` varchar(255) NOT NULL COMMENT '收件邮箱',
  `subject` varchar(255) DEFAULT NULL COMMENT '渲染后标题',
  `payload_json` json DEFAULT NULL COMMENT '模板变量与业务上下文',
  `scheduled_at` datetime(3) NOT NULL COMMENT '计划发送时间',
  `status` varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '状态 PENDING/VALIDATING/SENDING/SENT/FAILED/CANCELED/EXPIRED',
  `retry_count` int(11) NOT NULL DEFAULT 0 COMMENT '重试次数',
  `max_retry_count` int(11) NOT NULL DEFAULT 3 COMMENT '最大重试次数',
  `last_error` varchar(1024) DEFAULT NULL COMMENT '最近失败原因',
  `sent_at` datetime(3) DEFAULT NULL COMMENT '发送成功时间',
  `opened_at` datetime(3) DEFAULT NULL COMMENT '打开时间',
  `clicked_at` datetime(3) DEFAULT NULL COMMENT '点击时间',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_task_key` (`task_key`),
  KEY `idx_status_scheduled` (`status`, `scheduled_at`),
  KEY `idx_receiver_uid` (`receiver_uid`),
  KEY `idx_biz` (`biz_type`, `biz_id`),
  KEY `idx_template_status` (`template_code`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='邮件通知任务表';

CREATE TABLE IF NOT EXISTS `email_send_log` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '发送日志id',
  `task_id` bigint(20) UNSIGNED NOT NULL COMMENT '任务id',
  `provider` varchar(64) DEFAULT NULL COMMENT '邮件服务商',
  `provider_message_id` varchar(128) DEFAULT NULL COMMENT '服务商消息id',
  `email` varchar(255) NOT NULL COMMENT '收件邮箱',
  `send_status` varchar(32) NOT NULL COMMENT '发送状态 SUCCESS/FAIL',
  `error_code` varchar(64) DEFAULT NULL COMMENT '错误码',
  `error_message` varchar(1024) DEFAULT NULL COMMENT '错误信息',
  `request_id` varchar(128) DEFAULT NULL COMMENT '请求id',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_task_id` (`task_id`),
  KEY `idx_provider_message_id` (`provider_message_id`),
  KEY `idx_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='邮件发送日志表';

CREATE TABLE IF NOT EXISTS `lesson_summary` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '课后总结id',
  `lesson_id` bigint(20) UNSIGNED NOT NULL COMMENT '课节id，对应tutor_appointment.id',
  `course_id` bigint(20) UNSIGNED DEFAULT NULL COMMENT '长期课程id',
  `teacher_uid` bigint(20) UNSIGNED NOT NULL COMMENT '教师uid',
  `student_uid` bigint(20) UNSIGNED NOT NULL COMMENT '学生uid',
  `title` varchar(255) DEFAULT NULL COMMENT '总结标题',
  `summary_status` varchar(32) NOT NULL DEFAULT 'GENERATING' COMMENT '状态 GENERATING/READY/FAILED',
  `summary_brief` varchar(1000) DEFAULT NULL COMMENT '邮件摘要',
  `summary_content` mediumtext DEFAULT NULL COMMENT '完整总结内容',
  `homework` varchar(2000) DEFAULT NULL COMMENT '作业/建议',
  `ready_at` datetime(3) DEFAULT NULL COMMENT '生成完成时间',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_lesson_summary` (`lesson_id`),
  KEY `idx_course_id` (`course_id`),
  KEY `idx_student_ready` (`student_uid`, `summary_status`, `ready_at`),
  KEY `idx_teacher_ready` (`teacher_uid`, `summary_status`, `ready_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='课后总结表';
