CREATE TABLE IF NOT EXISTS `refund_request` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '退款申请id',
  `brokerage_order_id` bigint(20) UNSIGNED NOT NULL COMMENT '信息费订单id',
  `course_id` bigint(20) UNSIGNED DEFAULT NULL COMMENT '课程视图id（试课退款使用）',
  `room_id` bigint(20) UNSIGNED DEFAULT NULL COMMENT '会话id（聊天退款使用）',
  `applicant_uid` bigint(20) UNSIGNED NOT NULL COMMENT '申请人uid',
  `applicant_role` varchar(32) NOT NULL COMMENT '申请人角色 TEACHER/STUDENT',
  `type` varchar(32) NOT NULL COMMENT '退款类型 CHAT_INFO_FEE/TRIAL_INFO_FEE',
  `status` varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '申请状态 PENDING/APPROVED/REJECTED',
  `reason` varchar(1024) DEFAULT NULL COMMENT '退款原因/说明',
  `evidence_images_json` text COMMENT '证据图片URL数组（JSON）',
  `refund_percent` int(11) NOT NULL COMMENT '退款比例（100/60）',
  `refund_amount_fen` bigint(20) UNSIGNED NOT NULL COMMENT '申请退款金额（分）',
  `admin_uid` bigint(20) UNSIGNED DEFAULT NULL COMMENT '审核管理员uid',
  `admin_note` varchar(1024) DEFAULT NULL COMMENT '审核备注/拒绝原因',
  `decided_at` datetime(3) DEFAULT NULL COMMENT '审核时间',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_refund_request_status_type_time` (`status`, `type`, `create_time`),
  KEY `idx_refund_request_brokerage_status` (`brokerage_order_id`, `status`),
  KEY `idx_refund_request_room` (`room_id`),
  KEY `idx_refund_request_course` (`course_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='退款申请表（聊天退款/试课退款）';
