#!/bin/sh

set -eu

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

APP_REMOTE_USER="${APP_REMOTE_USER:-root}"
APP_REMOTE_HOST="${APP_REMOTE_HOST:-111.228.20.88}"
APP_REMOTE_PORT="${APP_REMOTE_PORT:-22}"
APP_REMOTE_PATH="${APP_REMOTE_PATH:-/opt/ai-platform}"
PROXY_REMOTE_USER="${PROXY_REMOTE_USER:-root}"
PROXY_REMOTE_HOST="${PROXY_REMOTE_HOST:-111.229.64.41}"
PROXY_REMOTE_PORT="${PROXY_REMOTE_PORT:-22}"
PROXY_REMOTE_PATH="${PROXY_REMOTE_PATH:-/opt/ai-platform}"
PUBLIC_DOMAIN="${PUBLIC_DOMAIN:-huoyue.online}"
PUBLIC_ADMIN_PORT="${PUBLIC_ADMIN_PORT:-5174}"
PUBLIC_ADMIN_BASE_PATH="${PUBLIC_ADMIN_BASE_PATH:-/admin/}"
REMOTE_MANAGE_INFRA="${REMOTE_MANAGE_INFRA:-never}"
REMOTE_NACOS_SERVER_ADDR="${REMOTE_NACOS_SERVER_ADDR:-127.0.0.1:8848}"
REMOTE_NACOS_GRPC_CHECK="${REMOTE_NACOS_GRPC_CHECK:-warn}"
REMOTE_SYNC_DELETE="${REMOTE_SYNC_DELETE:-1}"
TLS_CERT_PATH="${TLS_CERT_PATH:-}"
TLS_KEY_PATH="${TLS_KEY_PATH:-}"

echo "[public_test_up] 共享公网测试模式"
echo "[public_test_up] app=${APP_REMOTE_USER}@${APP_REMOTE_HOST}:${APP_REMOTE_PORT} path=$APP_REMOTE_PATH"
echo "[public_test_up] proxy=${PROXY_REMOTE_USER}@${PROXY_REMOTE_HOST}:${PROXY_REMOTE_PORT} path=$PROXY_REMOTE_PATH"
echo "[public_test_up] publicDomain=$PUBLIC_DOMAIN adminPath=$PUBLIC_ADMIN_BASE_PATH adminPort=$PUBLIC_ADMIN_PORT"

REMOTE_USER="$APP_REMOTE_USER" \
REMOTE_HOST="$APP_REMOTE_HOST" \
REMOTE_PORT="$APP_REMOTE_PORT" \
REMOTE_PATH="$APP_REMOTE_PATH" \
REMOTE_SYNC_DELETE="$REMOTE_SYNC_DELETE" \
bash scripts/sync_remote_code.sh

ssh -p "$APP_REMOTE_PORT" "${APP_REMOTE_USER}@${APP_REMOTE_HOST}" \
  "cd '$APP_REMOTE_PATH' && STOP_INFRA='0' sh scripts/dev_all_down.sh || true"

ssh -p "$APP_REMOTE_PORT" "${APP_REMOTE_USER}@${APP_REMOTE_HOST}" \
  "cd '$APP_REMOTE_PATH' && MANAGE_INFRA='$REMOTE_MANAGE_INFRA' NACOS_GRPC_CHECK='$REMOTE_NACOS_GRPC_CHECK' NACOS_SERVER_ADDR='$REMOTE_NACOS_SERVER_ADDR' FRONTEND_HOST='0.0.0.0' ADMIN_WEB_BASE_PATH='$PUBLIC_ADMIN_BASE_PATH' sh scripts/dev_all_up.sh"

ssh -p "$APP_REMOTE_PORT" "${APP_REMOTE_USER}@${APP_REMOTE_HOST}" \
  "cd '$APP_REMOTE_PATH' && ADMIN_BASE_PATH='$PUBLIC_ADMIN_BASE_PATH' sh scripts/setup_app_host_nginx.sh"

ssh -p "$PROXY_REMOTE_PORT" "${PROXY_REMOTE_USER}@${PROXY_REMOTE_HOST}" \
  "mkdir -p '$PROXY_REMOTE_PATH/scripts'"

scp -P "$PROXY_REMOTE_PORT" \
  scripts/setup_public_domain_proxy.sh \
  "${PROXY_REMOTE_USER}@${PROXY_REMOTE_HOST}:${PROXY_REMOTE_PATH}/scripts/"

ssh -p "$PROXY_REMOTE_PORT" "${PROXY_REMOTE_USER}@${PROXY_REMOTE_HOST}" \
  "cd '$PROXY_REMOTE_PATH' && PUBLIC_DOMAIN='$PUBLIC_DOMAIN' UPSTREAM_HOST='$APP_REMOTE_HOST' USER_WEB_PORT='80' ADMIN_WEB_PORT='$PUBLIC_ADMIN_PORT' ADMIN_API_PORT='18084' ADMIN_BASE_PATH='$PUBLIC_ADMIN_BASE_PATH' TLS_CERT_PATH='$TLS_CERT_PATH' TLS_KEY_PATH='$TLS_KEY_PATH' sh scripts/setup_public_domain_proxy.sh"

echo "[public_test_up] 用户端入口: http://$PUBLIC_DOMAIN/"
echo "[public_test_up] 管理端入口: http://$PUBLIC_DOMAIN$PUBLIC_ADMIN_BASE_PATH"
