#!/bin/sh

set -eu

REMOTE_USER="${REMOTE_USER:-root}"
REMOTE_HOST="${REMOTE_HOST:-111.229.64.41}"
REMOTE_PORT="${REMOTE_PORT:-22}"
REMOTE_PATH="${REMOTE_PATH:-/opt/ai-platform}"
PUBLIC_DOMAIN="${PUBLIC_DOMAIN:-}"
ADMIN_DOMAIN="${ADMIN_DOMAIN:-}"
NACOS_SERVER_ADDR="${NACOS_SERVER_ADDR:-111.228.20.88:8848}"
NACOS_GRPC_CHECK="${NACOS_GRPC_CHECK:-warn}"
SPRING_PROFILES_ACTIVE="${SPRING_PROFILES_ACTIVE:-dev}"
TLS_CERT_PATH="${TLS_CERT_PATH:-}"
TLS_KEY_PATH="${TLS_KEY_PATH:-}"
FRONTEND_HOST="${FRONTEND_HOST:-127.0.0.1}"
LEGACY_SYSTEMD_SERVICES="${LEGACY_SYSTEMD_SERVICES:-nginx}"

if [ -z "$PUBLIC_DOMAIN" ]; then
  echo "[run_remote_test_host_setup] 缺少 PUBLIC_DOMAIN，例如：PUBLIC_DOMAIN=pay.example.com"
  exit 1
fi

ssh -p "$REMOTE_PORT" "${REMOTE_USER}@${REMOTE_HOST}" \
  "cd '$REMOTE_PATH' && PUBLIC_DOMAIN='$PUBLIC_DOMAIN' ADMIN_DOMAIN='$ADMIN_DOMAIN' NACOS_SERVER_ADDR='$NACOS_SERVER_ADDR' NACOS_GRPC_CHECK='$NACOS_GRPC_CHECK' SPRING_PROFILES_ACTIVE='$SPRING_PROFILES_ACTIVE' TLS_CERT_PATH='$TLS_CERT_PATH' TLS_KEY_PATH='$TLS_KEY_PATH' FRONTEND_HOST='$FRONTEND_HOST' LEGACY_SYSTEMD_SERVICES='$LEGACY_SYSTEMD_SERVICES' bash scripts/setup_remote_test_host.sh"
